### ISSUE TITLE
typo in fucntion name "stream_read_scoket"

### ISSUE THREAD

**Issue by fabiangehring** [cran/sparklyr#1]
I guess this should be stream_read_socket (instead of stream_read_scoket).

**Comment by gaborcsardi** [comment]
Thanks, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file.

**Comment by fabiangehring** [comment]
Oh, sorry about that, didn't realize. Filed the issue on rstudios repo now.
